FROM node:14 as build

WORKDIR /app

#COPY package.json package-lock.json ./
COPY . .
RUN npm install

# Debug:
RUN ls -l /app && cat /app/package.json && npm run build

# RUN npm run build

FROM node:14 as runtime
WORKDIR /app
COPY --from=build /app/build ./build
EXPOSE 3000
CMD ["npm", "start"]
